# Generated by Django 3.2.18 on 2023-07-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensenamespace',
            name='isException',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='isException',
            field=models.BooleanField(default=True),
        ),
    ]
