name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci # For JavaScript linting (replace with your package manager command)

      - name: Run ESLint
        run: npx eslint . --ext .js --fix

      - name: Run HTMLHint
        run: npx htmlhint . --format json | npx htmlhint-reporter-pretty --reporter stdout --severity error --quiet

      - name: Run Stylelint
        run: npx stylelint . --quiet --fix

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install -r requirements.txt # For Python linting (replace with your command)

      - name: Run Pylint
        run: pylint --fix --load-plugins pylint_quotes,pylint.extensions.docparams .
